USE [FSLRPWithDapperMongoDB]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Taxas](
	[Codigo] [int] NOT NULL,
	[Valor] [float] NULL,
	[Fator] [float] NULL,
 CONSTRAINT [PK_Taxas] PRIMARY KEY CLUSTERED 
(
	[Codigo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

INSERT INTO Taxas SELECT 1, 10, 2
GO